[project]
name = "dbt-aron"
version = "0.1.0"
description = "My insights after some time working with dbt in a pharma company."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt>=1.0.0.40.6",
    "dbt-core>=1.10.13",
    "dbt-postgres>=1.9.1",
]
